### PR TITLE
Store version in version.json file, read by both app and gradle.

### PR DESCRIPTION
**Pull request by gijskant**
With these changes, version updates have to be put in only two places:
- `src/app/config/version.json` (used by the application and by gradle)
- `package.json`

### CODE REVIEW

**Comment by beaugogh** [comment]
there is a ticket corresponding to this issue, TMT-56, plz follow the comments there

**Comment by beaugogh** [comment]
as what we have talked about, the puppet does not need to overwrite everything in the config.default.json. In principle, puppet shouldn't overwrite anything in the config, different deployment of glowingbear will have different config.default.json's, which is the only place where glowingbear-related config is set. A secondary approach would be puppet overwriting only the part it needs for individual glowingbear deployment, leaving the rest of the config options untouched.

**Comment by beaugogh** [comment]
Using as few config (or manual input) files as possible would be recommended in our future development

**Comment by gijskant** [comment]
Having as few as possible configuration files is one thing, I my view it is also good to have sensible defaults and only having to configure specific config values in the config file.

**Comment by gijskant** [comment]
Close this in favour of #446, which stores the version in `config.default.json` instead of in a separate `version.json` file.

**Pull request closed without merging**
